debug: false
ingress:
  enabled: true
  includeDefaultExtraAnnotations: true
  extraAnnotations:
    "kubernetes.io/tls-acme": "true"
    "cert-manager.io/cluster-issuer": "example.com-letsencrypt-issuer"
    "kubernetes.io/ingress.class": "nginx"
#    "nginx.ingress.kubernetes.io/server-snippet": |-
#      deny 192.168.0.1;
#      allow 192.168.0.0/8;
#      deny all;
  tls:
    # options: rancher, letsEncrypt, secret
    source: secret
    secretName: tls-rancher-ingress

replicas: 1
tls: ingress
