image:
  repository: jutze/embyserver
  pullPolicy: IfNotPresent
  tag: 4.7.6.0-self

env:
  TZ: Asia/Shanghai
  UID: 1000
  GID: 1000
  GIDLIST: "33,100"

service:
  main:
    enabled: false
  emby:
    enabled: true
    ports:
      http:
        enabled: true
        port: 8096

ingress:
  emby:
    enabled: true
    primary: true
    annotations:
      helm.sh/resource-policy: keep
      kubernetes.io/tls-acme: "true"
      cert-manager.io/cluster-issuer: example.com-letsencrypt-issuer
    ingressClassName: "nginx"
    hosts:
      - host: mov.example.com
        paths:
        - path: /
          pathType: Prefix
          service:
            name: emby
            port: 8096
    tls:
    - hosts:
      - mov.example.com
      secretName: mov.example.com-tls      

persistence:
  config:
    enabled: true
    type: pvc
    mountPath: /config
    storageClass: local-zfs-sc
    accessMode: ReadWriteOnce
    size: 10Gi
    retain: true

#  photo:
#    enabled: true
#    type: hostPath
#    hostPath: /mnt/some-disk/photo
#    mountPath: /mnt/photo