image:
  repository: jellyfin/jellyfin
  pullPolicy: IfNotPresent
  tag: 10.8.8

env:
  TZ: Asia/Shanghai

service:
  main:
    enabled: false
  jellyfin:
    enabled: true
    ports:
      http:
        enabled: true
        port: 8096

ingress:
  jellyfin:
    enabled: true
    primary: true
    annotations:
      helm.sh/resource-policy: keep
      kubernetes.io/tls-acme: "true"
      cert-manager.io/cluster-issuer: example.com-letsencrypt-issuer
    ingressClassName: "nginx"
    hosts:
      - host: fun.example.com
        paths:
        - path: /
          pathType: Prefix
          service:
            name: jellyfin
            port: 8096
    tls:
    - hosts:
      - fun.example.com
      secretName: fun.example.com-tls      

persistence:
  config:
    enabled: true
    type: pvc
    mountPath: /config
    storageClass: local-zfs-sc
    accessMode: ReadWriteOnce
    size: 100Gi
    retain: true
  cache:
    enabled: true
    type: pvc
    mountPath: /cache
    storageClass: local-zfs-sc
    accessMode: ReadWriteOnce
    size: 100Gi
    retain: true

#  photo:
#    enabled: true
#    type: hostPath
#    hostPath: /mnt/some-disk/photo
#    mountPath: /mnt/photo